import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main flex justify-center items-center bg-slate-600 h-screen">
        <div className="container max-w-screen-lg"></div>
      </div>
    </div>
  );
};

export default Home;
