import type { NextPage } from "next";
import Head from "next/head";
import { useState, useEffect, useCallback, useMemo } from "react";
import Grid from "./components/grid";

const Home: NextPage = () => {
  const [attempts, setAttempts] = useState<string[]>([]);
  const [currentAttempt, setCurrentAttempt] = useState<string>("");
  const [currentAttemptIndex, setCurrentAttemptIndex] = useState<number>(0);

  useMemo(() => {
    let genAttempts = new Array<string>(6).fill("");
    setAttempts(genAttempts);
  }, []);

  useEffect(() => {
    const handleType = (e: any) => {
      if (currentAttemptIndex > 5) return;
      setCurrentAttempt((currentAttempt) => currentAttempt + e.key);
    };

    window.addEventListener("keydown", handleType);

    return () => {
      window.removeEventListener("keydown", handleType);
    };
  }, []);

  useEffect(() => {
    if (currentAttempt.length % 5 === 0) {
      console.log(currentAttemptIndex);
      setCurrentAttempt("");
      setCurrentAttemptIndex((currentAttemptIndex) => currentAttemptIndex + 1);
    }
    let newAttempt = [...attempts];
    newAttempt[currentAttemptIndex] = currentAttempt;
    setAttempts(newAttempt);
  }, [currentAttempt]);

  return (
    <div>
      <Head>
        <title>Worldle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="main flex justify-center items-center bg-slate-600 h-screen w-full">
        <div className="container max-w-screen-lg h-full flex justify-center items-center flex-col">
          <h1 className="title text-center text-3xl font-semibold">Wordle</h1>
          <h2 className="text-xl">
            Start Typing to see the <strong>magic</strong>{" "}
          </h2>
          <Grid attempts={attempts} currentAttempt={currentAttempt} />
        </div>
      </div>
    </div>
  );
};

export default Home;
